# Generated by Django 2.2.24 on 2023-12-05 20:03

from django.db import migrations


def set_value_to_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year > 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20231205_2005'),
    ]

    operations = [
        migrations.RunPython(set_value_to_new_building),
    ]
