# Generated by Django 2.2.24 on 2023-12-07 16:17
#+77010643693
#+7 701 064 3693
from django.db import migrations
import phonenumbers


def normalization_of_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        number = flat.owners_phonenumber
        flat.owner_pure_phone = phonenumbers.parse(number, "RU")
        if phonenumbers.is_valid_number(flat.owner_pure_phone):
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20231207_1612'),
    ]

    operations = [
        migrations.RunPython(normalization_of_phone_numbers, move_backward),
    ]
