# Generated by Django 2.2.24 on 2023-12-07 19:40

from django.db import migrations


def copy_owners_data_in_flat_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for flat in Owner.objects.all():
        flat.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owners_data_in_flat_to_owners,
                             move_backward),
    ]
