# Generated by Django 2.2.24 on 2023-12-07 20:09

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20231207_2340'),
    ]

    operations = [
    ]
